# Hilbert Matrix

In [1]:
import numpy as np

In [2]:
def hilbert_matrix(n):
    H = np.zeros((n,n))
    for i in range(n):
        for j in range(n):
            H[i,j] = 1/(i+1+j)
    return H

<strong>Example 1:</strong> Generate the Hilbert Matrix with n = 2, 3, 4, 5

In [3]:
print("\n*****************************")
print("n = 2")
print("H")
H1 = hilbert_matrix(2)
print(H1)

print("\n*****************************")
print("n = 3")
print("H")
H2 = hilbert_matrix(3)
print(H2)

print("\n*****************************")
print("n = 4")
print("H")
H3 = hilbert_matrix(4)
print(H3)

print("\n*****************************")
print("n = 5")
print("H")
H4 = hilbert_matrix(5)
print(H4)


*****************************
n = 2
H
[[1.         0.5       ]
 [0.5        0.33333333]]

*****************************
n = 3
H
[[1.         0.5        0.33333333]
 [0.5        0.33333333 0.25      ]
 [0.33333333 0.25       0.2       ]]

*****************************
n = 4
H
[[1.         0.5        0.33333333 0.25      ]
 [0.5        0.33333333 0.25       0.2       ]
 [0.33333333 0.25       0.2        0.16666667]
 [0.25       0.2        0.16666667 0.14285714]]

*****************************
n = 5
H
[[1.         0.5        0.33333333 0.25       0.2       ]
 [0.5        0.33333333 0.25       0.2        0.16666667]
 [0.33333333 0.25       0.2        0.16666667 0.14285714]
 [0.25       0.2        0.16666667 0.14285714 0.125     ]
 [0.2        0.16666667 0.14285714 0.125      0.11111111]]
