# LU Factorization

We will try to find the matrices L and U such that A=LU

In [1]:
import numpy as np

In [2]:
def LU(A, b):
    n = b.size
    L = np.zeros((n,n))
    U = np.zeros((n,n))
    for k in range(n):
        for r in range(n):
            U[k,r] = A[k,r] 
            if k == r:
                L[k,r] = 1
            if k < r:
                factor = A[r,k]/A[k,k]
                L[r,k] = factor
                for c in range(0,n):
                    A[r,c] = A[r,c] - factor*A[k,c]
                    U[r,c] = A[r,c]
    return [L,U]

def back_subs(L,U,b):
    n = b.size
    x = np.zeros(n)
    c = np.zeros(n)
    
    c[0] = b[0]/L[0,0]
    for l in range(1,n):
        s = 0
        for m in range(0,l):
            s = s + L[l,m]*c[m]
        c[l] = (b[l] - s)/L[l,l]
    
    for l in range(n-1,-1,-1):
        t = 0
        for m in range(l+1,n):
            t = t + U[l,m]*x[m]
        x[l] = (c[l] - t)/U[l,l]
    return [c,x]

<strong>Example 1:</strong>Solve the system by finding the LU factorization and the carrying out the two-step back substitution.

A = 
$\begin{bmatrix} 3 & 1 & 2 \\ 6 & 3 & 4 \\ 3 & 1 & 5 \end{bmatrix}$, 
b = 
$\begin{bmatrix} 0 \\ 1 \\ 3 \end{bmatrix}$


In [3]:
A1 = np.matrix('3 1 2; 6 3 4; 3 1 5')
b1 = np.array([[0],[1],[3]])
[L1, U1] = LU(A1, b1)
print("\nL = ")
print(L1)
print("\nU = ")
print(U1)
print("\nA = LU = ")
print(L1.dot(U1))
[c1, x1] = back_subs(L1,U1,b1)
print("\nx = ")
print(x1)
print("\nb = Ax")
print(A1.dot(x1))


L = 
[[1. 0. 0.]
 [2. 1. 0.]
 [1. 0. 1.]]

U = 
[[3. 1. 2.]
 [0. 1. 0.]
 [0. 0. 3.]]

A = LU = 
[[3. 1. 2.]
 [6. 3. 4.]
 [3. 1. 5.]]

x = 
[-1.  1.  1.]

b = Ax
[[0. 1. 3.]]


<strong>Example 2:</strong>Solve the system by finding the LU factorization and the carrying out the two-step back substitution.

A = 
$\begin{bmatrix} 4 & 2 & 0 \\ 4 & 4 & 2 \\ 2 & 2 & 3 \end{bmatrix}$, 
b = 
$\begin{bmatrix} 2 \\ 4 \\ 6 \end{bmatrix}$


In [4]:
A2 = np.matrix('4 2 0; 4 4 2; 2 2 3')
b2 = np.array([[2],[4],[6]])
[L2, U2] = LU(A2, b2)
print("\nL = ")
print(L2)
print("\nU = ")
print(U2)
print("\nA = LU = ")
print(L2.dot(U2))
[c2, x2] = back_subs(L2, U2, b2)
x2.shape = (3, 1)
print("\nx = ")
print(x2)
print("\nb = Ax")
print((L2.dot(U2)).dot(x2))


L = 
[[1.  0.  0. ]
 [1.  1.  0. ]
 [0.5 0.5 1. ]]

U = 
[[4. 2. 0.]
 [0. 2. 2.]
 [0. 0. 2.]]

A = LU = 
[[4. 2. 0.]
 [4. 4. 2.]
 [2. 2. 3.]]

x = 
[[ 1.]
 [-1.]
 [ 2.]]

b = Ax
[[2.]
 [4.]
 [6.]]
