# Naive Gaussian Elimination

In [1]:
import numpy as np

In [2]:
def naive_gaussian(A,b):
    n = b.size
    for j in range(n-1):
        for i in range(j+1,n):
            mult = A[i,j]/A[j,j]
            for k in range(j+1,n):
                A[i,k] = A[i,k] - mult*A[j,k]
            b[i] = b[i] - mult*b[j]
    c = b
    x = np.ones(n)
    for l in range(n-1,-1,-1):
        for m in range(l+1,n):
            c[l] = c[l] - A[l,m]*x[m]
        x[l] = b[l]/A[l,l]
    return x

<strong>Example 1:</strong> Use the naive-Gaussian Method to solve the following system of equations:

* $2x - 2y - z = -2$

  $4x + y - 2y = 1$
  
  $-2x + y - z = -3$
  

In [3]:
A = np.matrix('2 -2 -1; 4 1 -2; -2 1 -1')
b = np.array([-2, 1, -3])
print("A = ")
print(A)
print("")
print("b = ")
print(b)

print('\n ************** Solution: ************* \n')
sol = naive_gaussian(A, b)
print("The solution is: {}".format(sol))

A = 
[[ 2 -2 -1]
 [ 4  1 -2]
 [-2  1 -1]]

b = 
[-2  1 -3]

 ************** Solution: ************* 

The solution is: [1. 1. 2.]


<strong>Example 2:</strong> Use the naive-Gaussian Method to solve the following system of equations:
  
* $x + 2y - z = 2$

  $    3y + z = 4$
  
  $2x - y + z = 2$

In [4]:
A = np.matrix('1 2 -1; 0 3 1; 2 -1 1')
b = np.array([2, 4, 2])
print("A = ")
print(A)
print("")
print("b = ")
print(b)

print('\n ************** Solution: ************* \n')
sol = naive_gaussian(A, b)
print("The solution is: {}".format(sol))

A = 
[[ 1  2 -1]
 [ 0  3  1]
 [ 2 -1  1]]

b = 
[2 4 2]

 ************** Solution: ************* 

The solution is: [1. 1. 1.]


<strong>Example 3:</strong> Let H denote the nxn Helbert matrix, whose(i,j) entry is 1/(i+j-1). Find the Solution for Hx=b for n = 5, and b is the vector of all ones.

In [5]:
def hilbert_matrix(n):
    H = np.zeros((n,n))
    for i in range(n):
        for j in range(n):
            H[i,j] = 1/(i+1+j)
    return H

In [6]:
H = hilbert_matrix(5)
b1 = np.ones(5)

print("H = ")
print(H)
print("")
print("b = ")
print(b1)

print('\n ************** Solution: ************* \n')
sol = naive_gaussian(H, b1)
print("The solution is: {}".format(sol))

H = 
[[1.         0.5        0.33333333 0.25       0.2       ]
 [0.5        0.33333333 0.25       0.2        0.16666667]
 [0.33333333 0.25       0.2        0.16666667 0.14285714]
 [0.25       0.2        0.16666667 0.14285714 0.125     ]
 [0.2        0.16666667 0.14285714 0.125      0.11111111]]

b = 
[1. 1. 1. 1. 1.]

 ************** Solution: ************* 

The solution is: [    5.  -120.   630. -1120.   630.]
