# LU Factorization

We will try to find the matrices L and U such that A=LU

In [1]:
import numpy as np

In [2]:
def PLU_factorization(A):
    n = int(np.sqrt(A.size))
    L = np.zeros((n,n), dtype='float64')
    U = np.zeros((n,n), dtype='float64')
    P = np.identity(n)
    for k in range(n):
        print("")
        print(A)
        for i in range(k,n):
            if A[k,k] < A[i,k]:
                tempA = A[k,:].copy()
                tempP = P[k,:].copy()
                A[k,:] = A[i,:]
                P[k,:] = P[i,:]
                A[i,:] = tempA
                P[i,:] = tempP
        print("")
        print(A)
        for r in range(n):
            U[k,:] = A[k,:] 
            if k == r:
                L[k,r] = 1
            if k < r:
                factor = A[r,k]/A[k,k]
                L[r,k] = factor
                A[r,:] = A[r,:] - factor*A[k,:]
                U[r,:] = A[r,:] 

    return [P,L,U]


def back_subs(L,U,b):
    n = b.size
    x = np.zeros(n)
    c = np.zeros(n)
    
    c[0] = b[0]/L[0,0]
    for l in range(1,n):
        s = 0
        for m in range(0,l):
            s = s + L[l,m]*c[m]
        c[l] = (b[l] - s)/L[l,l]
    
    for l in range(n-1,-1,-1):
        t = 0
        for m in range(l+1,n):
            t = t + U[l,m]*x[m]
        x[l] = (c[l] - t)/U[l,l]
    return [c,x]


<strong>Example 1:</strong> Find the PA=LU factorization of the matrix

A = 
$\begin{bmatrix} 2 & 1 & 5 \\ 4 & 4 & -4 \\ 1 & 3 & 1 \end{bmatrix}$, 

In [3]:
A = np.matrix([[2, 1, 5],[4, 4, -4], [1, 3 , 1]], dtype='float64')

[P, L, U] = PLU_factorization(A)

print("\n P = ")
print(P)
print("\n L = ")
print(L)
print("\n U = ")
print(U)


[[ 2.  1.  5.]
 [ 4.  4. -4.]
 [ 1.  3.  1.]]

[[ 4.  4. -4.]
 [ 2.  1.  5.]
 [ 1.  3.  1.]]

[[ 4.  4. -4.]
 [ 0. -1.  7.]
 [ 0.  2.  2.]]

[[ 4.  4. -4.]
 [ 0.  2.  2.]
 [ 0. -1.  7.]]

[[ 4.  4. -4.]
 [ 0.  2.  2.]
 [ 0.  0.  8.]]

[[ 4.  4. -4.]
 [ 0.  2.  2.]
 [ 0.  0.  8.]]

 P = 
[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]

 L = 
[[ 1.    0.    0.  ]
 [ 0.5   1.    0.  ]
 [ 0.25 -0.5   1.  ]]

 U = 
[[ 4.  4. -4.]
 [ 0.  2.  2.]
 [ 0.  0.  8.]]


<strong>Example 2:</strong> Use the $PA = LU$ factorization to solve the system $Ax = b$, where

$A = \begin{bmatrix} 2 & 1 & 5 \\ 4 & 4 & -4 \\ 1 & 3 & 1\end{bmatrix}$,  $b = \begin{bmatrix} 5 \\ 0 \\ 6 \end{bmatrix}$ 

In [4]:
A = np.matrix([[2, 1, 5],[4, 4, -4], [1, 3 , 1]], dtype='float64')
b = np.array([5,0,6])

[P, L, U] = PLU_factorization(A)

[c, x] = back_subs(L,U,P.dot(b))

print(x)


[[ 2.  1.  5.]
 [ 4.  4. -4.]
 [ 1.  3.  1.]]

[[ 4.  4. -4.]
 [ 2.  1.  5.]
 [ 1.  3.  1.]]

[[ 4.  4. -4.]
 [ 0. -1.  7.]
 [ 0.  2.  2.]]

[[ 4.  4. -4.]
 [ 0.  2.  2.]
 [ 0. -1.  7.]]

[[ 4.  4. -4.]
 [ 0.  2.  2.]
 [ 0.  0.  8.]]

[[ 4.  4. -4.]
 [ 0.  2.  2.]
 [ 0.  0.  8.]]
[-1.  2.  1.]


<strong>Example 3:</strong> Solve the system $2x_{1} + 3x_{2} = 4$, $3x_{1} + 2x_{2} = 1$ using the PA = LU factorization with partial pivoting

In [5]:
A = np.matrix('2 3; 3 2', 'float64')
print("\n A = ")
print(A)

b = np.array([4, 1])
print("\n b = ")
print(b)

[P, L, U] = PLU_factorization(A)

print("\n L = ")
print(L)

print("\n U = ")
print(U)

print("\n P = ")
print(P)

[c, x] = back_subs(L, U, P.dot(b))
print("\nx = ")
print(x)





 A = 
[[2. 3.]
 [3. 2.]]

 b = 
[4 1]

[[2. 3.]
 [3. 2.]]

[[3. 2.]
 [2. 3.]]

[[3.         2.        ]
 [0.         1.66666667]]

[[3.         2.        ]
 [0.         1.66666667]]

 L = 
[[1.         0.        ]
 [0.66666667 1.        ]]

 U = 
[[3.         2.        ]
 [0.         1.66666667]]

 P = 
[[0. 1.]
 [1. 0.]]

x = 
[-1.  2.]
