# Cholesky Factorization

In [1]:
import numpy as np

In [107]:
def cholesky(A):
    A1 = A.copy()
    n = np.shape(A1)[0]
    R = np.zeros((n,n))
    for i in range(n):
        R[i,i] = np.sqrt(A1[i,i])
        u_t = (1/R[i,i])*A1[i,i+1:]
        U = np.outer(u_t,u_t)
        R[i,i+1:] = u_t 
        A1[i+1:,i+1:] = A1[i+1:,i+1:] - U
    return [R, R.T]

In [108]:
def back_subs(L,U,b):
    n = b.size
    x = np.zeros(n)
    c = np.zeros(n)
    
    c[0] = b[0]/L[0,0]
    for l in range(1,n):
        s = 0
        for m in range(0,l):
            s = s + L[l,m]*c[m]
        c[l] = (b[l] - s)/L[l,l]
    
    for l in range(n-1,-1,-1):
        t = 0
        for m in range(l+1,n):
            t = t + U[l,m]*x[m]
        x[l] = (c[l] - t)/U[l,l]
    return [c,x]

# Example 1
* Solve Ax = b Using cholesky factorization

In [114]:
A = np.array([[4,-2,2],[-2,2,-4],[2,-4,11]])
print(A)

[[ 4 -2  2]
 [-2  2 -4]
 [ 2 -4 11]]


In [115]:
b = np.array([[3],[-7],[3]])
print(b)

[[ 3]
 [-7]
 [ 3]]


In [116]:
[R,R_T] = cholesky(A)
print(R)
print(R_T)
print(A)

[[ 2. -1.  1.]
 [ 0.  1. -3.]
 [ 0.  0.  1.]]
[[ 2.  0.  0.]
 [-1.  1.  0.]
 [ 1. -3.  1.]]
[[ 4 -2  2]
 [-2  2 -4]
 [ 2 -4 11]]


In [117]:
[c,x] = back_subs(R_T,R,b)
print(x)

[-17.  -50.5 -15. ]


In [118]:
A.dot(x)

array([ 3., -7.,  3.])