In [153]:
%run hilbert_matrix.ipynb
import numpy as np

In [154]:
def conj_grad_meth(A,b,x0):
    n = len(b)
    r = list()
    d = list()
    z = 0 #alpha value
    w = 0 #beta value
    x = list()
    x.append(x0)
    r.append(b - A.dot(x[0]))
    d.append(b - A.dot(x[0]))
    
    
    for i in range(len(b)):
        if r[i].all() == 0:
            print("done")
            print(i)
            break
        else:
            z = (r[i].dot(r[i]))/d[i].dot(A.dot(d[i]))
            x.append( x[i] + z*d[i])
            r.append( r[i] - z*A.dot(d[i]))
            w = (r[i+1].dot(r[i+1]))/r[i].dot(r[i])
            d.append(r[i+1] + w*d[i])
    return x[-1]    
        

In [155]:
A = np.array([[2,2],[2,5]])
b = np.array([6,3])
print(A)
print(b)

[[2 2]
 [2 5]]
[6 3]


In [156]:
x0 = np.array([0,0])
x = conj_grad_meth(A,b,x0)
x

array([ 4., -1.])

In [158]:
H = hilbert(4)
b1 = np.ones(4)
x0 = np.zeros(4)

x = conj_grad_meth(H,b1,x0) 
print(x)

[  -4.   60. -180.  140.]
