# Naive Gaussian Elimination

We will try to find the solution of the following system of equations using the naive Gausian elimination method. Find the solution of the following: 

x + 2y - z = 3;
2x + y -2x = 3;
-3x + y + z = -6;

Note: This does not take into account zeros in the main diagonal

In [108]:
import numpy as np

In [109]:
def naive_gaussian(A,b):
    n = b.size
    for j in range(0,n-1):
        for i in range(j+1,n):
            mult = A[i,j]/A[j,j]
            for k in range(j,n):
                A[i,k] = A[i,k] - mult*A[j,k]
            b[i] = b[i] - mult*b[j]
    c = b
    x = np.ones(n)
    for l in range(n-1,-1,-1):
        for m in range(l+1,n):
            c[l] = c[l] - A[l,m]*x[m]
        x[l] = b[l]/A[l,l]
    return [A,b,x]

In [110]:
A = np.array([[1, 2, -1],[2, 1, -2], [-3, 1 , 1]])
b = np.array([[3, 3, -6]]).T
print(A)
print(b)

[[ 1  2 -1]
 [ 2  1 -2]
 [-3  1  1]]
[[ 3]
 [ 3]
 [-6]]


In [111]:
[A_new,b_new,x] = naive_gaussian(A,b)
print("\n ****************************************\n")
print("A_modified = ")
print(A_new)
print("\n *************************************** \n")
print("b_modified = ")
print(b_new)
print("\n *************************************** \n")
print("Solution = ")
print(x)


 ****************************************

A_modified = 
[[ 1  2 -1]
 [ 0 -3  0]
 [ 0  0 -2]]

 *************************************** 

b_modified = 
[[ 3]
 [-3]
 [-4]]

 *************************************** 

Solution = 
[ 3.  1.  2.]


Example 2:

Let H denote the nxn Helbert matrix, whose(i,j) entry is 1/(i+j-1). Find the Solution for Hx=b for n = 5, and b is the vector of all ones.

In [115]:
def Hilbert(n):
    H = np.zeros((n,n))
    for i in range(n):
        for j in range(n):
            H[i,j] = 1/(i+1+j)
    return H

In [116]:
H = Hilbert(5)
H

array([[ 1.        ,  0.5       ,  0.33333333,  0.25      ,  0.2       ],
       [ 0.5       ,  0.33333333,  0.25      ,  0.2       ,  0.16666667],
       [ 0.33333333,  0.25      ,  0.2       ,  0.16666667,  0.14285714],
       [ 0.25      ,  0.2       ,  0.16666667,  0.14285714,  0.125     ],
       [ 0.2       ,  0.16666667,  0.14285714,  0.125     ,  0.11111111]])

In [118]:
b1 = np.ones(5)
b1

array([ 1.,  1.,  1.,  1.,  1.])

In [119]:
[H_mod, b_mod, x_sol] = naive_gaussian(H,b1)

In [120]:
print("\n ****************************************\n")
print("H_modified = ")
print(H_mod)
print("\n *************************************** \n")
print("b_modified = ")
print(b_mod)
print("\n *************************************** \n")
print("Solution = ")
print(x_sol)


 ****************************************

H_modified = 
[[  1.00000000e+00   5.00000000e-01   3.33333333e-01   2.50000000e-01
    2.00000000e-01]
 [  0.00000000e+00   8.33333333e-02   8.33333333e-02   7.50000000e-02
    6.66666667e-02]
 [  0.00000000e+00  -1.38777878e-17   5.55555556e-03   8.33333333e-03
    9.52380952e-03]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   3.57142857e-04
    7.14285714e-04]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
    2.26757370e-05]]

 *************************************** 

b_modified = 
[ 5.         -10.          3.5        -0.4         0.01428571]

 *************************************** 

Solution = 
[    5.  -120.   630. -1120.   630.]
